[build]
  command = "npx prisma db push --accept-data-loss && npx prisma db seed && npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NETLIFY_SECRETS_SCAN_ENABLED = "false"

[functions]
  included_files = ["prisma/dev.db"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
